// scripts/collections-serializer.ts
/* eslint-disable no-control-regex */

type Network = "Base" | "Arbitrum" | "Degen" | "Ethereum" | "Celo"

type ActionLabelOverride = {
  miniapp?: string
  opensea?: string
}

export type Collection = {
  id: string
  name: string
  creators: string[]
  miniapp?: string
  opensea?: string
  network: Network
  thumbnail: string
  highlight?: boolean
  primaryActionLabelOverride?: ActionLabelOverride
  secondaryActionLabelOverride?: ActionLabelOverride
}

export type Group = {
  title: string
  description: string
  itemIds: string[]
  featuredId?: string
}

export type CollectionsState = {
  collectionsById: Record<string, Collection>
  groups: Group[]
}

function esc(s: string): string {
  // JSON.stringify handles quotes + control chars
  return JSON.stringify(s)
}

function isNonEmpty(s: unknown): s is string {
  return typeof s === "string" && s.trim().length > 0
}

function stableStringifyObj(obj: Record<string, unknown>, indent = 2): string {
  return JSON.stringify(obj, null, indent)
}

function fmtOverride(ov?: ActionLabelOverride): string | null {
  if (!ov) return null
  const out: Record<string, string> = {}
  if (isNonEmpty(ov.miniapp)) out.miniapp = ov.miniapp.trim()
  if (isNonEmpty(ov.opensea)) out.opensea = ov.opensea.trim()
  if (!Object.keys(out).length) return null
  return stableStringifyObj(out)
}

function fmtCollection(c: Collection): string {
  const lines: string[] = []
  lines.push(`  ${esc(c.id)}: {`)
  lines.push(`    id: ${esc(c.id)},`)
  lines.push(`    name: ${esc(c.name)},`)
  lines.push(`    creators: ${stableStringifyObj(c.creators)},`)

  if (isNonEmpty(c.miniapp)) lines.push(`    miniapp: ${esc(c.miniapp.trim())},`)
  if (isNonEmpty(c.opensea)) lines.push(`    opensea: ${esc(c.opensea.trim())},`)

  lines.push(`    network: ${esc(c.network)},`)

  if (c.highlight) lines.push(`    highlight: true,`)

  lines.push(`    thumbnail: ${esc(c.thumbnail)},`)

  const p = fmtOverride(c.primaryActionLabelOverride)
  const s = fmtOverride(c.secondaryActionLabelOverride)
  if (p) lines.push(`    primaryActionLabelOverride: ${p},`)
  if (s) lines.push(`    secondaryActionLabelOverride: ${s},`)

  lines.push(`  },`)
  return lines.join("\n")
}

function fmtGroup(g: Group): string {
  const lines: string[] = []
  lines.push(`  {`)
  lines.push(`    title: ${esc(g.title)},`)
  lines.push(`    description: ${esc(g.description)},`)
  if (isNonEmpty(g.featuredId)) lines.push(`    featuredId: ${esc(g.featuredId.trim())},`)
  lines.push(`    itemIds: ${stableStringifyObj(g.itemIds)},`)
  lines.push(`  },`)
  return lines.join("\n")
}

export function serializeCollectionsTs(state: CollectionsState, buildDateLabel?: string): string {
  const ids = Object.keys(state.collectionsById)

  // stable output for clean diffs
  ids.sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }))

  const header = `// src/data/collections.ts
// AUTO-GENERATED BY scripts/editor-server.ts
// Last saved${buildDateLabel ? `: ${buildDateLabel}` : ""}

export type Network = "Base" | "Arbitrum" | "Degen" | "Ethereum" | "Celo"

// shared override type
export type ActionLabelOverride = {
  miniapp?: string
  opensea?: string
}

export type Collection = {
  id: string
  name: string
  creators: string[]
  miniapp?: string
  opensea?: string
  network: Network
  thumbnail: string
  highlight?: boolean

  // Button label overrides (per-link-type)
  primaryActionLabelOverride?: ActionLabelOverride
  secondaryActionLabelOverride?: ActionLabelOverride
}

export type Group = {
  title: string
  description: string
  itemIds: string[]
  featuredId?: string
}

// Single source of truth: define each collection once.
export const collectionsById: Record<string, Collection> = {
`

  const bodyCollections = ids.map(id => fmtCollection(state.collectionsById[id])).join("\n\n")

  const mid = `}
  
// Groups reference collections by ID, no duplication.
export const groups: Group[] = [
`

  const bodyGroups = state.groups.map(fmtGroup).join("\n\n")

  const tail = `]
`

  return header + bodyCollections + "\n" + mid + bodyGroups + "\n" + tail
}
