// src/data/collections-archive.ts
// AUTO-GENERATED BY scripts/editor-server.ts
// Archived collections are appended here.

import type { Collection } from "./collections"

export const collectionsArchiveById: Record<string, Collection> = {
  "og-nft":   {
      "id": "og-nft",
      "name": "OG NFTs",
      "creators": [
        "@primenode.eth"
      ],
      "miniapp": "https://nft-factory.kasra.codes/mint/gRP3zv10_Q",
      "network": "Base",
      "thumbnail": "/thumbs/og.png"
    },
}
