// src/data/collections.ts
// AUTO-GENERATED BY scripts/editor-server.ts
// Last saved: Dec 30, 2025

export type Network = "Base" | "Arbitrum" | "Degen" | "Ethereum" | "Celo"

// shared override type
export type ActionLabelOverride = {
  miniapp?: string
  opensea?: string
}

export type Collection = {
  id: string
  name: string
  creators: string[]
  miniapp?: string
  opensea?: string
  network: Network
  thumbnail: string
  highlight?: boolean

  // Button label overrides (per-link-type)
  primaryActionLabelOverride?: ActionLabelOverride
  secondaryActionLabelOverride?: ActionLabelOverride
}

export type Group = {
  title: string
  description: string
  itemIds: string[]
  featuredId?: string
}

// Single source of truth: define each collection once.
export const collectionsById: Record<string, Collection> = {
  "arblets": {
    id: "arblets",
    name: "Arblets",
    creators: [
  "@0xanas.eth"
],
    opensea: "https://opensea.io/collection/the-arblets",
    network: "Arbitrum",
    thumbnail: "/thumbs/arblets.png",
  },

  "base-punks": {
    id: "base-punks",
    name: "Base Punks",
    creators: [
  "@gmonchain.eth"
],
    opensea: "https://opensea.io/collection/basepunkz-on-base",
    network: "Base",
    thumbnail: "/thumbs/base-punks.png",
  },

  "based-build": {
    id: "based-build",
    name: "Based Build",
    creators: [
  "@mevmonk"
],
    miniapp: "https://basedbuilds.xyz/share?token=3&tx=0x0c33ab7d327ee94e28b1714a174fe097cdd251ee222d13799da23e559636c1b6",
    opensea: "https://opensea.io/collection/basedbuilds",
    network: "Base",
    thumbnail: "/thumbs/based-build.png",
  },

  "cloakies": {
    id: "cloakies",
    name: "Cloakies",
    creators: [
  "@blainemalone"
],
    opensea: "https://opensea.io/collection/cloakies-collection",
    network: "Base",
    thumbnail: "/thumbs/cloakies.png",
  },

  "cryptoadickbutts": {
    id: "cryptoadickbutts",
    name: "CryptoaDickButts",
    creators: [
  "@madyak"
],
    opensea: "https://opensea.io/collection/cryptoadickbuttz",
    network: "Base",
    thumbnail: "/thumbs/cryptoadickbutts.png",
  },

  "dickpunks": {
    id: "dickpunks",
    name: "DickPunks",
    creators: [
  "@madyak"
],
    miniapp: "https://farcaster.xyz/miniapps/2vgEwTqkDV2n/crytpodickpunks-mint",
    opensea: "https://opensea.io/collection/cryptodickpunks-on-base",
    network: "Base",
    highlight: true,
    thumbnail: "/thumbs/dickpunkslive.png",
  },

  "farape-apes": {
    id: "farape-apes",
    name: "Farape Apes",
    creators: [
  "@recessdotfun"
],
    miniapp: "https://farcaster.xyz/miniapps/sqYk09wRm676/farape",
    network: "Base",
    thumbnail: "/thumbs/farape.png",
  },

  "farcaster-constellation": {
    id: "farcaster-constellation",
    name: "Farcaster Social Constellation NFTs",
    creators: [
  "@jesse7.eth"
],
    miniapp: "https://farcaster.xyz/miniapps/1QWOndscTLyV/social-constellation-nft",
    network: "Base",
    thumbnail: "/thumbs/constellation.png",
  },

  "farcaster-dino": {
    id: "farcaster-dino",
    name: "Farcaster Dinos",
    creators: [
  "@0xsayan.eth"
],
    miniapp: "https://farcaster.xyz/miniapps/Pjm_FOONcY1K/farcaster-dinos-mint",
    network: "Arbitrum",
    thumbnail: "/thumbs/dinos.png",
  },

  "farcaster-interns": {
    id: "farcaster-interns",
    name: "Farcaster Interns",
    creators: [
  "@Unknown"
],
    opensea: "https://opensea.io/collection/farcaster-interns-3",
    network: "Base",
    thumbnail: "/thumbs/farcaster-interns.png",
  },

  "farcaster-pro-og": {
    id: "farcaster-pro-og",
    name: "Farcaster Pro OGs",
    creators: [
  "@miguelgarest.eth"
],
    opensea: "https://opensea.io/collection/farcaster-pro-og",
    network: "Base",
    thumbnail: "/thumbs/pro.png",
  },

  "farpixel-cats": {
    id: "farpixel-cats",
    name: "FarPixel Cats",
    creators: [
  "@farpixel",
  "@Attilagaliba.eth"
],
    miniapp: "https://farcaster.xyz/miniapps/dU0eSxtWRBvf/farpixel",
    opensea: "https://opensea.io/collection/farpixelcats",
    network: "Base",
    thumbnail: "/thumbs/farpixel-cats.png",
  },

  "fid-azuki": {
    id: "fid-azuki",
    name: "FID Azukis",
    creators: [
  "@ritukumari.eth"
],
    opensea: "https://opensea.io/collection/fidazuki",
    network: "Base",
    thumbnail: "/thumbs/fid-azuki.png",
  },

  "fid-mfers": {
    id: "fid-mfers",
    name: "fidMfers",
    creators: [
  "@smolemaru"
],
    miniapp: "TBA",
    network: "Base",
    thumbnail: "/thumbs/fid-mfer.png",
  },

  "fid-punks": {
    id: "fid-punks",
    name: "FID Punks",
    creators: [
  "@streetphoto"
],
    opensea: "https://opensea.io/collection/fidpunks",
    network: "Base",
    thumbnail: "/thumbs/fid-punks.png",
  },

  "frosty-friends": {
    id: "frosty-friends",
    name: "Frosty Friends",
    creators: [
  "@primenode.eth"
],
    miniapp: "https://farcaster.xyz/miniapps/38mV7ok9eAKi/frosty-friends",
    opensea: "https://opensea.io/collection/frosty-friends-677973055",
    network: "Base",
    thumbnail: "/thumbs/frosty-friends.png",
  },

  "howlers": {
    id: "howlers",
    name: "Howlers",
    creators: [
  "@sharas.eth"
],
    miniapp: "https://farcaster.xyz/miniapps/yBlGKitosGjY/howlers",
    opensea: "https://opensea.io/collection/howlers-on-base",
    network: "Base",
    thumbnail: "/thumbs/howlers.png",
  },

  "immutagen": {
    id: "immutagen",
    name: "immutagen",
    creators: [
  "@mfbevan.eth"
],
    miniapp: "https://farcaster.xyz/miniapps/77Z7J_ZHttit/immutagen",
    network: "Base",
    thumbnail: "/thumbs/immutagen.png",
    primaryActionLabelOverride: {
  "miniapp": "Open"
},
  },

  "mogpunks": {
    id: "mogpunks",
    name: "MogPunks",
    creators: [
  "@xexcy"
],
    miniapp: "https://mogpunks-mint.vercel.app/",
    opensea: "https://opensea.io/collection/mogpunks",
    network: "Base",
    thumbnail: "/thumbs/mogpunks.png",
  },

  "not-punks": {
    id: "not-punks",
    name: "Not Punks",
    creators: [
  "@pratiksharma.eth"
],
    miniapp: "https://farcaster.xyz/miniapps/lvNNJ5A8VRiK/not-punks",
    network: "Base",
    thumbnail: "/thumbs/notpunks.png",
  },

  "okcomputers": {
    id: "okcomputers",
    name: "OK Computers",
    creators: [
  "@dailofrog"
],
    opensea: "https://opensea.io/collection/okcomputers",
    network: "Base",
    thumbnail: "/thumbs/okcomputers.png",
  },

  "paint-people": {
    id: "paint-people",
    name: "Paint People",
    creators: [
  "@iamtaylor"
],
    miniapp: "http://paintpeople.vercel.app/",
    opensea: "https://opensea.io/collection/biggerpaintpeople",
    network: "Base",
    thumbnail: "/thumbs/paint-people.png",
  },

  "petlets": {
    id: "petlets",
    name: "Petlets",
    creators: [
  "@sayangel"
],
    miniapp: "https://www.harmonybot.xyz/share/petlets/254221",
    opensea: "https://opensea.io/collection/petlets",
    network: "Base",
    thumbnail: "/thumbs/petlets.png",
  },

  "pixel-noun": {
    id: "pixel-noun",
    name: "Pixel Nouns Bot",
    creators: [
  "@markcarey"
],
    miniapp: "https://farcaster.xyz/miniapps/JBWDbpN3nSow/pixel-nouns",
    opensea: "https://explorer.degen.tips/token/0x6fB0F96Bb2dCD32388eBBB6b13608928Ed538218",
    network: "Degen",
    thumbnail: "/thumbs/pixel-nouns-bot.png",
    secondaryActionLabelOverride: {
  "opensea": "View"
},
  },

  "probots": {
    id: "probots",
    name: "Probots",
    creators: [
  "@procoin"
],
    opensea: "https://opensea.io/collection/probots",
    network: "Base",
    thumbnail: "/thumbs/probots.png",
  },

  "protardio": {
    id: "protardio",
    name: "Protardios",
    creators: [
  "@protardio",
  "@q",
  "@kuusho"
],
    miniapp: "https://farcaster.xyz/miniapps/MqVtma_28MiI/protardio",
    opensea: "https://opensea.io/collection/protardio-citizens",
    network: "Base",
    thumbnail: "/thumbs/protardio.png",
  },

  "rock": {
    id: "rock",
    name: "x402 Rocks",
    creators: [
  "@x402rocks"
],
    miniapp: "https://farcaster.xyz/miniapps/AqmkuW0oc7Fk/x402rocks-mint-live",
    network: "Celo",
    thumbnail: "/thumbs/rocks.png",
  },

  "sheeplet": {
    id: "sheeplet",
    name: "Sheeplets",
    creators: [
  "@basewtf"
],
    miniapp: "https://thesheeplets.gobase.wtf/",
    opensea: "https://opensea.io/item/base/0x756325fb738cf88197997cf6e5fc1bfb18963dcd/584",
    network: "Base",
    thumbnail: "/thumbs/sheeplet.png",
  },

  "sophlet": {
    id: "sophlet",
    name: "Sophlets",
    creators: [
  "@chriscocreated"
],
    miniapp: "https://immutagen.ai/mint/d964d9a2-6707-4b3e-98a5-c505ae0d04d1?generationId=978c332b-aa9d-42c0-b8d0-7c044ca023a9",
    opensea: "https://opensea.io/collection/sophlets",
    network: "Base",
    highlight: true,
    thumbnail: "/thumbs/sophlets.png",
  },

  "sweep": {
    id: "sweep",
    name: "sweep.zone",
    creators: [
  "@horsefacts.eth"
],
    miniapp: "https://farcaster.xyz/miniapps/B94B28OhXPTH/sweepzone",
    network: "Base",
    thumbnail: "/thumbs/sweep.png",
    primaryActionLabelOverride: {
  "miniapp": "Open"
},
  },

  "the-apostles": {
    id: "the-apostles",
    name: "The Apostles",
    creators: [
  "@jesus"
],
    miniapp: "https://farcaster.xyz/miniapps/y3JyVxonCq_o/the-apostles",
    opensea: "https://opensea.io/collection/the-apostles-929464319",
    network: "Base",
    highlight: true,
    thumbnail: "/thumbs/the-apostles.png",
  },

  "the-barcode": {
    id: "the-barcode",
    name: "The Barcode",
    creators: [
  "@thebarcode"
],
    miniapp: "https://farcaster.xyz/miniapps/lGupNaXO2fv8/the-barcode",
    opensea: "https://opensea.io/collection/the-barcode-farcaster",
    network: "Base",
    thumbnail: "/thumbs/barcode.png",
  },

  "tiny-turtles": {
    id: "tiny-turtles",
    name: "Tiny Turtles",
    creators: [
  "@mfbevan.eth"
],
    miniapp: "https://immutagen.ai/mint/c1244fe2-7b40-43c4-871f-c8ed4c13ab83?generationId=6838adb0-e66e-4229-8350-91b518b46efd",
    opensea: "https://opensea.io/collection/the-tiny-turtles",
    network: "Base",
    thumbnail: "/thumbs/tiny-turtles.png",
  },

  "uniko": {
    id: "uniko",
    name: "Unikō",
    creators: [
  "@miguelgarest.eth"
],
    opensea: "https://opensea.io/collection/uniko-by-miguelgarest",
    network: "Base",
    thumbnail: "/thumbs/uniko.png",
  },

  "waifu": {
    id: "waifu",
    name: "Waifus",
    creators: [
  "@eggman.eth"
],
    miniapp: "https://farcaster.xyz/miniapps/_NawZqxwVR8H/waifu",
    opensea: "https://opensea.io/collection/base-waifus",
    network: "Base",
    thumbnail: "/thumbs/waifu.png",
  },

  "waifulets": {
    id: "waifulets",
    name: "Waifulets",
    creators: [
  "@eggman.eth"
],
    opensea: "https://opensea.io/collection/waifulets",
    network: "Base",
    thumbnail: "/thumbs/waifulets.png",
  },

  "warplet-babies": {
    id: "warplet-babies",
    name: "Warplet Babies",
    creators: [
  "@markcarey"
],
    miniapp: "https://farcaster.xyz/miniapps/iyhggRrAsWJK/warplet-babies",
    network: "Base",
    thumbnail: "/thumbs/babies.png",
  },

  "warplet-mash-up": {
    id: "warplet-mash-up",
    name: "Warplet Mash Up",
    creators: [
  "@alec.eth"
],
    miniapp: "https://warplet-mashup.vercel.app/mashup/1766299224302-doo0vrdt3?participants=sayangel%2Clevertz&image=https%3A%2F%2Fcoral-sophisticated-albatross-902.mypinata.cloud%2Fipfs%2FQmNWvYmsSZMXrqt2iz36v7sWbKatNzzhZm3rgzSGqTU5E2",
    network: "Base",
    thumbnail: "/thumbs/warplet-mash-up.png",
  },

  "warplet-mfer": {
    id: "warplet-mfer",
    name: "Warplet Mfers",
    creators: [
  "@markcarey"
],
    miniapp: "https://farcaster.xyz/miniapps/XQktyvz1H9zn/warplet-mfers",
    network: "Base",
    thumbnail: "/thumbs/mfer.png",
  },

  "warplet-nouns": {
    id: "warplet-nouns",
    name: "Warplet Nouns",
    creators: [
  "@markcarey"
],
    miniapp: "https://farcaster.xyz/miniapps/Pvs6xfVCnvqn/warplet-nouns",
    network: "Base",
    thumbnail: "/thumbs/nouns.png",
  },

  "warplet-sweaters": {
    id: "warplet-sweaters",
    name: "Warplet Sweaters",
    creators: [
  "@markcarey"
],
    miniapp: "https://warpletsweaters.frm.lol/warpletsweaters/minted/bafybeifsroay74hao3sctvjxfekvuvtmzhg6azofbbseawj2ixqmc7bzku",
    network: "Base",
    thumbnail: "/thumbs/warplet-sweaters.png",
  },

  "warplets": {
    id: "warplets",
    name: "The Warplets",
    creators: [
  "@sayangel"
],
    opensea: "https://opensea.io/collection/the-warplets-farcaster",
    network: "Base",
    thumbnail: "/thumbs/warplets.png",
  },

  "wecastwarplets-49k-mint": {
    id: "wecastwarplets-49k-mint",
    name: "WeCast Warplets",
    creators: [
  "@chriscocreated"
],
    miniapp: "https://farcaster.xyz/miniapps/DLMNg-iBux-P/wecastwarplets-49k-mint",
    opensea: "https://opensea.io/assets/base/0x71423af9132f5d33001dac560ab943ad4a503a66/7",
    network: "Base",
    thumbnail: "/thumbs/wecast.png",
  },

  "wordlets": {
    id: "wordlets",
    name: "Wordlets",
    creators: [
  "@0xspencer"
],
    miniapp: "https://farcaster.xyz/miniapps/2BLcqRzDLTXv/wordlets",
    network: "Base",
    thumbnail: "/thumbs/wordlets.png",
  },

  "world-computer": {
    id: "world-computer",
    name: "World Computer",
    creators: [
  "@Unknown"
],
    opensea: "https://opensea.io/collection/worldcomputerclub",
    network: "Base",
    thumbnail: "/thumbs/world-computer.png",
  },

  "x402-toadz": {
    id: "x402-toadz",
    name: "x402 Toadz",
    creators: [
  "@maxbuidl.eth"
],
    opensea: "https://opensea.io/collection/x402_toadz-club-base",
    network: "Base",
    thumbnail: "/thumbs/x402-toadz.png",
  },
}
  
// Groups reference collections by ID, no duplication.
export const groups: Group[] = [
  {
    title: "Alpha",
    description: "Mints incoming. Check in again for updates",
    featuredId: "fid-mfers",
    itemIds: [],
  },

  {
    title: "Live",
    description: "Time to click buttons. The following limited and open edition mints are live.",
    featuredId: "dickpunks",
    itemIds: [
  "petlets",
  "protardio",
  "waifu",
  "sophlet",
  "based-build",
  "the-apostles",
  "pixel-noun",
  "paint-people"
],
  },

  {
    title: "Warplet-ification",
    description: "NFTs that are derivatives of your Warplet(s)",
    featuredId: "petlets",
    itemIds: [
  "warplets",
  "warplet-mfer",
  "warplet-nouns",
  "warplet-babies",
  "warplet-sweaters",
  "warplet-mash-up",
  "wordlets"
],
  },

  {
    title: "Legacy",
    description: "Mint has ended (or just lost momentum and never minted out)",
    featuredId: "warplets",
    itemIds: [
  "waifulets",
  "uniko",
  "cloakies",
  "base-punks",
  "fid-punks",
  "fid-azuki",
  "arblets",
  "world-computer",
  "cryptoadickbutts",
  "farcaster-interns",
  "x402-toadz",
  "rock",
  "probots",
  "okcomputers",
  "farcaster-dino",
  "not-punks",
  "mogpunks",
  "farpixel-cats",
  "tiny-turtles",
  "the-barcode",
  "farape-apes",
  "sheeplet",
  "wecastwarplets-49k-mint",
  "howlers",
  "farcaster-pro-og",
  "farcaster-constellation",
  "frosty-friends"
],
  },

  {
    title: "Other Cool Miniapps",
    description: "Some other cool miniapps related to Farcaster NFTs collection curation",
    featuredId: "sweep",
    itemIds: [
  "immutagen"
],
  },
]
